function h=slidevar(varname,limit, T0c,f)
if nargin==4
    
    T0c=GetHMatrix(T0c);
    RPY=tr2rpy(T0c);
    
    offset=40;
    offset2=0;
    
    h = figure('pos',[400 400 400 400],...
        'menubar','none',...
        'numbertitle','off',...
        'name',varname);
    hs = uicontrol(h,...
        'style','slider',...
        'pos',[offset+30 280 260 20],...
        'min',limit(1,1),...
        'max',limit(1,2),...
        'value',T0c(1,4),...
        'callback',@sliderupdate,...
        'tag',varname);
    
    TEXT = uicontrol(h,...
        'style','text',...
        'pos',[offset+300 280 50 20],...
        'String',num2str(T0c(1,4)),...
        'tag','TEXT');
    
    Label = uicontrol(h,...
        'style','text',...
        'pos',[offset2+10 280 50 20],...
        'String','X',...
        'tag','Label');
    
    hs1 = uicontrol(h,...
        'style','slider',...
        'pos',[offset+30 240 260 20],...
        'min',limit(2,1),...
        'max',limit(2,2),...
        'value',T0c(2,4),...
        'callback',@sliderupdate1,...
        'tag',varname);
    
    TEXT1 = uicontrol(h,...
        'style','text',...
        'pos',[offset+300 240 50 20],...
        'String',T0c(2,4),...
        'tag','TEXT1');
    
    Label1 = uicontrol(h,...
        'style','text',...
        'pos',[offset2+10 240 50 20],...
        'String','Y',...
        'tag','Label1');
    
    hs2 = uicontrol(h,...
        'style','slider',...
        'pos',[offset+30 200 260 20],...
        'min',limit(3,1),...
        'max',limit(3,2),...
        'value',T0c(3,4),...
        'callback',@sliderupdate2,...
        'tag',varname);
    
     TEXT2 = uicontrol(h,...
        'style','text',...
        'pos',[offset+300 200 50 20],...
        'String',T0c(3,4),...
        'tag','TEXT2');
    
     Label2 = uicontrol(h,...
        'style','text',...
        'pos',[offset2+10 200 50 20],...
        'String','Z',...
        'tag','Label2');
    
    hs3 = uicontrol(h,...
        'style','slider',...
        'pos',[offset+30 160 260 20],...
        'min',limit(4,1),...
        'max',limit(4,2),...
        'value',RPY(1),...
        'callback',@sliderupdate3,...
        'tag',varname);
    
    TEXT3 = uicontrol(h,...
        'style','text',...
        'pos',[offset+300 160 50 20],...
        'String',RPY(1),...
        'tag','TEXT3');
    
    Label3 = uicontrol(h,...
        'style','text',...
        'pos',[offset2+10 160 50 20],...
        'String','Rot_x',...
        'tag','Label3');
    
    hs4 = uicontrol(h,...
        'style','slider',...
        'pos',[offset+30 120 260 20],...
        'min',limit(5,1),...
        'max',limit(5,2),...
        'value',RPY(2),...
        'callback',@sliderupdate4,...
        'tag',varname);
    
    TEXT4 = uicontrol(h,...
        'style','text',...
        'pos',[offset+300 120 50 20],...
        'String',RPY(2),...
        'tag','TEXT4');
    
    Label4 = uicontrol(h,...
        'style','text',...
        'pos',[offset2+10 120 50 20],...
        'String','Rot_y',...
        'tag','Label4');
    
    hs5 = uicontrol(h,...
        'style','slider',...
        'pos',[offset+30 80 260 20],...
        'min',limit(6,1),...
        'max',limit(6,2),...
        'value',RPY(3),...
        'callback',@sliderupdate5,...
        'tag',varname);
     
    TEXT5 = uicontrol(h,...
        'style','text',...
        'pos',[offset+300 80 50 20],...
        'String',RPY(3),...
        'tag','TEXT5');
    
    Label5 = uicontrol(h,...
        'style','text',...
        'pos',[offset2+10 80 50 20],...
        'String','Rot_z',...
        'tag','Label_5');
    
    hs6 = uicontrol(h,...
        'style','slider',...
        'pos',[offset+30 340 260 20],...
        'min',limit(7,1),...
        'max',limit(7,2),...
        'value',f,...
        'callback',@sliderupdate6,...
        'tag',varname);
     
    TEXT6 = uicontrol(h,...
        'style','text',...
        'pos',[offset+300 340 50 20],...
        'String',f,...
        'tag','TEXT6');
    
    Label6 = uicontrol(h,...
        'style','text',...
        'pos',[offset2+10 340 50 20],...
        'String','Focal Length',...
        'tag','Label_6');
    
    hs7= uicontrol(h,...
        'style','pushbutton',...
        'string','QUIT',...
        'pos',[190 20 50 50],...
        'callback',@pushbutton_callback,...
        'tag',varname);
    
    
    if nargout==0
        clear h
    end
end

function pushbutton_callback(varargin)
v = get(varargin{1},'tag');
assignin('base', get(varargin{1},'tag'), v)
close(gcbf)

function sliderupdate(varargin)
ht = findobj(gcbf, 'style','text');
v = get(varargin{1},'value');
set(findobj(gcbf,'Tag','TEXT'),'String',num2str(v))
% set(ht, 'string', num2str(v))
assignin('base', get(varargin{1},'tag'), v)

function sliderupdate1(varargin)
ht = findobj(gcbf, 'style','text');
v = get(varargin{1},'value');
set(findobj(gcbf,'Tag','TEXT1'),'String',num2str(v))
% set(ht, 'string', num2str(v))
assignin('base', get(varargin{1},'tag'), v)

function sliderupdate2(varargin)
ht = findobj(gcbf, 'style','text');
v = get(varargin{1},'value');
set(findobj(gcbf,'Tag','TEXT2'),'String',num2str(v))
% set(ht, 'string', num2str(v))
assignin('base', get(varargin{1},'tag'), v)

function sliderupdate3(varargin)
ht = findobj(gcbf, 'style','text');
v = get(varargin{1},'value');
set(findobj(gcbf,'Tag','TEXT3'),'String',num2str(v))
% set(ht, 'string', num2str(v))
assignin('base', get(varargin{1},'tag'), v)

function sliderupdate4(varargin)
ht = findobj(gcbf, 'style','text');
v = get(varargin{1},'value');
set(findobj(gcbf,'Tag','TEXT4'),'String',num2str(v))
% set(ht, 'string', num2str(v))
assignin('base', get(varargin{1},'tag'), v)

function sliderupdate5(varargin)
ht = findobj(gcbf, 'style','text');
v = get(varargin{1},'value');
set(findobj(gcbf,'Tag','TEXT5'),'String',num2str(v))
% set(ht, 'string', num2str(v))
assignin('base', get(varargin{1},'tag'), v)

function sliderupdate6(varargin)
ht = findobj(gcbf, 'style','text');
v = get(varargin{1},'value');
set(findobj(gcbf,'Tag','TEXT6'),'String',num2str(v))
% set(ht, 'string', num2str(v))
assignin('base', get(varargin{1},'tag'), v)


